x-aes: &aes
  depends_on:
    init:
      condition: service_completed_successfully
  image: ${image}:${tag}-aes
  user: ${UID}:${GID}
  volumes:
  - ${PWD}:${PWD}
  - volume:/var/lib/inaccel
  working_dir: ${PWD}
x-aes-environment: &aes-environment
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  in: ${in:?The in variable is not set.}
  out: ${out:?The out variable is not set.}
  pass: ${pass}
services:
  aes-128-cbc:
    <<: *aes
    environment:
      <<: *aes-environment
      cipher: aes-128-cbc
  aes-192-cbc:
    <<: *aes
    environment:
      <<: *aes-environment
      cipher: aes-192-cbc
  aes-256-cbc:
    <<: *aes
    environment:
      <<: *aes-environment
      cipher: aes-256-cbc
  aes-128-cfb:
    <<: *aes
    environment:
      <<: *aes-environment
      cipher: aes-128-cfb
  aes-192-cfb:
    <<: *aes
    environment:
      <<: *aes-environment
      cipher: aes-192-cfb
  aes-256-cfb:
    <<: *aes
    environment:
      <<: *aes-environment
      cipher: aes-256-cfb
  aes-128-ctr:
    <<: *aes
    environment:
      <<: *aes-environment
      cipher: aes-128-ctr
  aes-192-ctr:
    <<: *aes
    environment:
      <<: *aes-environment
      cipher: aes-192-ctr
  aes-256-ctr:
    <<: *aes
    environment:
      <<: *aes-environment
      cipher: aes-256-ctr
  init:
    command:
    - bitstream
    - install
    - ${repository}/${platform}/${bitstream}
    image: inaccel/cli
    volumes:
    - volume:/var/lib/inaccel
volumes:
  volume:
    driver: inaccel
